defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: come_home_development

test:
  <<: *defaults
  database: come_home_test

# set these environment variables on your prod server
production:
  <<: *defaults
  database: come_home
  username: <%= ENV['COME_HOME_MONGO_USERNAME'] %>
  password: <%= ENV['COME_HOME_MONGO_PASSWORD'] %>
